# Generated by Django 5.1.1 on 2024-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_app', '0004_badge_profile_badges_poemreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('insightful', 'Insightful'), ('beautiful', 'Beautiful'), ('inspiring', 'Inspiring'), ('sad', 'Sad'), ('funny', 'Funny'), ('thoughtful', 'Thoughtful'), ('uplifting', 'Uplifting')], max_length=10),
        ),
    ]
