# Generated by Django 5.1.1 on 2024-10-08 10:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_app', '0005_alter_reaction_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='poemreaction',
            name='poetry_app__user_id_0d5eef_idx',
        ),
        migrations.AlterUniqueTogether(
            name='poemreaction',
            unique_together={('user', 'poem', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='poemreaction',
            index=models.Index(fields=['user', 'poem', 'reaction_type'], name='poetry_app__user_id_cb77ac_idx'),
        ),
    ]
