# Generated by Django 5.1.1 on 2024-12-21 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_app', '0010_tag_photographer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
