# Generated by Django 5.1.1 on 2024-12-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_app', '0011_delete_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
